### ISSUE TITLE
Audio Files are Distorted when imported to Ableton Live

### ISSUE THREAD

**Issue by cozma** [LibraryOfCongress/citizen-dj#14]
<img width="1660" alt="Screen Shot 2020-04-27 at 10 14 26 AM" src="https://user-images.githubusercontent.com/5613132/80382203-003e0280-8870-11ea-89b9-1658676bfa24.png">

When attempting to import any audio sample into Ableton Live 10, the wavelengths are completely distorted like above. This might be caused by some frequency compression either on the site or the original export of the files. I attempted this on multiple samples from different audio collections. You can see the exact sample for the image above in the bottom left corner.

Acceptance Criteria:
- Downloaded audio files can be properly played back in Ableton Live.

**Comment by beefoo** [comment]
thank you, @cozma!  this is the type of technical user testing i needed.

if it's possible, can you send me two files:
(1) the wav file that you linked above in the screenshot
(2) _any_ wav file that does work in your Ableton Live 10... it could be anything.  i just would like to compare the two on my machine

You can upload them to my dropbox:
https://www.dropbox.com/request/agxFc8AQ0JYOdlf121yE

And lastly, what OS are you using?

**Comment by cozma** [comment]
> thank you, @cozma! this is the type of technical user testing i needed.
> 
> if it's possible, can you send me two files:
> (1) the wav file that you linked above in the screenshot
> (2) _any_ wav file that does work in your Ableton Live 10... it could be anything. i just would like to compare the two on my machine
> 
> You can upload them to my dropbox:
> https://www.dropbox.com/request/agxFc8AQ0JYOdlf121yE
> 
> And lastly, what OS are you using?

No problem, happy to help!
I uploaded a random sample I've used `KSHMR_Cello_17_Melody_120_Dm.wav` and the file from the screenshot to the Dropbox. My OS is **OSX 10.11.6**

**Comment by ttruiett** [comment]
hey @cozma, just found Citizen DJ today. 

I've downloaded a few songs from there this morning and have imported them into Ableton Live 10.1.3 with no issues or distortion.

I'm on OS X 10.14.6


Edit: Nvmind, my mistake. MP3's work fine, but wav files have the same issue listed for me.

**Comment by beefoo** [comment]
@cozma I have a feeling this might be because the wav format is 32-bit, can you try out this file that's 16-bit?

https://www.dropbox.com/s/fdtyf20pxzmepk5/A-better-America_2001642615_004_00-00-30.wav?dl=1

If that works, I should probably just export these at 16-bit since the source material is 16-bit (i.e. no quality gain for increasing bit depth).  Thanks again for helping troubleshoot this.

**Comment by cozma** [comment]
> @cozma I have a feeling this might be because the wav format is 32-bit, can you try out this file that's 16-bit?
> 
> https://www.dropbox.com/s/fdtyf20pxzmepk5/A-better-America_2001642615_004_00-00-30.wav?dl=1
> 
> If that works, I should probably just export these at 16-bit since the source material is 16-bit (i.e. no quality gain for increasing bit depth). Thanks again for helping troubleshoot this.

Yes, this file works! Thanks for looking into it

**Comment by beefoo** [comment]
that's great to hear!   I've updated the .wav files on the website, so hopefully things will work now.  Apologies for having to re-download everything
