### ISSUE TITLE
Share button link does not reproduce pattern accurately

### ISSUE THREAD

**Issue by jehlers42** [LibraryOfCongress/citizen-dj#17]
Clicking the share button produces a link you can copy & paste into a browser to replicate the pattern. Using that link does not reproduce the pattern correctly, however.

Original pattern:
![image](https://user-images.githubusercontent.com/19698281/80409684-24a0db80-887e-11ea-8b6e-fc9b22c9e19a.png)

Pattern "reproduced" by using Share link:
![image](https://user-images.githubusercontent.com/19698281/80409714-34b8bb00-887e-11ea-9d6b-0488752594f1.png)

This is the link generate by Share:
http://citizendj.labs.loc.gov.s3-website-us-east-1.amazonaws.com/loc-variety-stage/remix/?patternEdits=0%3D7%2C4%2C12%261%3D3%2C11%2C9%263%3D10%264%3D2%2C10%2C14%2C12%2C6%2C4%265%3D8%2C14%2C4%266%3D2%2C6%267%3D15%2C14%2C6&bpm=93&itemId=00694051&itemStart=204730&drumName=Akai%20MPC&patternName=80s%20hip%20hop%20pattern%20A%20%5B1%5D

**Comment by beefoo** [comment]
The sharing URL feature has been refactored (to be much shorter) and should work as expected now.  Here's the new URL that reproduces your pattern:

https://citizen-dj.labs.loc.gov/loc-variety-stage/remix/?e=0_10!1_4-2-6-10-12-14!2_4-8-14!3_6-2!4_9-11-3!5_7-4-12!6_6-14-15&i=00694051&s=204730&d=mpc&p=80hA1
