### ISSUE TITLE
[Feature Request] Export Loop Remix Option

### ISSUE THREAD

**Issue by timendez** [LibraryOfCongress/citizen-dj#21]
Hi there,

I would really benefit from being able to download a remix as-is. Just getting a .wav file would be extremely helpful!

Today I exported a loop by recording my headphone output via Audacity, and then chopped it up the best I could but it took a while and I couldn't get a perfect loop.

Fantastic project you've got here. Great work!

**Comment by beefoo** [comment]
A tentative first pass of this has been implemented, tested on Chrome, Firefox, and Safari.  Exports current loop as a .wav file that should be a seamless loop.  Still needs more in-depth testing, so keeping this issue open for now.

![Annotation 2020-06-30 215952](https://user-images.githubusercontent.com/67169/86276807-94478580-bba3-11ea-8f6c-dafd587b6031.png)

**Comment by timendez** [comment]
Thank you @beefoo!
