### ISSUE TITLE
Save current work

### ISSUE THREAD

**Issue by pilatePete** [LibraryOfCongress/citizen-dj#22]
A person can create a groove but is unable to save their work.

Or maybe I just didn't see the option.

I'm using a smart phone...

**Comment by beefoo** [comment]
I added a basic feature that allows users to save patterns in their browser:
![Annotation 2020-08-18 095212](https://user-images.githubusercontent.com/67169/90527346-72986280-e13f-11ea-809a-da96c6e343d5.png)
