### ISSUE TITLE
Clip Duration Slider value changes the size of the window depending on Value Decimal

### ISSUE THREAD

**Issue by mrbombmusic** [LibraryOfCongress/citizen-dj#37]
When using the Clip Duration slider in the Remix mode, the value changes the size of the window as well as the placement of the word "duration" in relation to the word "clip" which causes a visual jittery effect.

If the value has zero, one or two decimal places (3, 1.3, 0.78), the word "duration" is next to the word "clip"
![Screen Shot 2020-09-10 at 2 27 35 PM](https://user-images.githubusercontent.com/26189509/92781222-ee1db600-f371-11ea-88f2-cb6694bab731.png)

But if the value has 3 decimal places, the word "duration" moves below the word "clip" which causes all the other elements below that word to move as well (particularly the waveform).
![Screen Shot 2020-09-10 at 2 27 46 PM](https://user-images.githubusercontent.com/26189509/92781149-df370380-f371-11ea-92ba-a28a4728c8a8.png)

All those elements are constantly moving up and down as you change the slider value as a result of this. Perhaps just have the slider value always read with 3 decimals regardless (1.000, 1.010, 1.100 etc)

I noticed a similar issue with the clip start slider, but that only affects the slider track moving back and forth as the decimal values change.

I would also like to suggest reducing the amount of time for the clip duration slider to allow for easier fine tuning of samples. It seems unlikely someone would want to have a 10-20 second sample when they only have 4 beats to work with. Maybe 5 seconds at most to allow for easier fine tuning with the slider. It seems more likely someone would prefer to be able to easily shave a couple decimal points off of the duration with the slider. I realize this can be done with the keyboard arrows but that may not be obvious to everyone.

Love the project!!!

**Comment by beefoo** [comment]
Thank you for catching this!  I applied a fix for this; as you saw, the slider was automatically resizing based on the length of the decimal places.  So I applied a fixed with for both labels.

You should see the change take effect in the next 24 hours, thanks again!
