### ISSUE TITLE
Question about National Jukebox Collection samples and their inclusion in Citizen DJ

### ISSUE THREAD

**Issue by Zyberetro** [LibraryOfCongress/citizen-dj#40]
Hi. I'm a fan of Citizen DJ, and I had a question about it that prompted me to make a GitHub account just to ask this one question. There's a lot of really cool samples to explore and use in music projects of various genres. The acoustical era recordings from the Variety Stage and Inventing Entertainment collections for example are full of vintage lo-fi character and are practically tailor-made for lo-fi music.

Which is why I was excited for 2022, as at the bottom of the Citizen DJ homepage, there is a teaser for new samples arriving in 2022. Clicking on "Learn more" shows an explanation of what is coming in 2022, namely over 10000 sound recordings from a collection called the "National Jukebox Collection" that will become public domain due to copyright expiration. The thing is though, as of writing this (January 4th, 2022), those samples **are** in the public domain, but the page is still written like this hasn't happened yet, as the page asks you to "Check back here on January 1, 2022!" 

I figured that maybe the 1922 and earlier recordings would be available for download on the Library of Congress website, as they weren't available before presumably due to them still being copyrighted, but the Jukebox samples that are from 1922 and earlier aren't available for download either, even though they are now in the public domain. To be clear, I used the link provided on the Citizen DJ webpage that automatically filters out recordings from after 1922 to make sure I wasn't trying to download recordings from 1923 onwards.

I decided to check the Citizen DJ GitHub to see what was going on, and on the thread titled "Search for a particular spoken word or phrase" (I'm not using a link because I'm not sure if GitHub will permit me posting links), Brian stated that Citizen DJ is currently frozen due to him departing from the project in October 2020, I assume this is why Citizen DJ wasn't updated in 2022 with the National Jukebox samples. If it's okay for me to ask, I'd love some clarification as to the status of Citizen DJ and whether the National Jukebox samples will be added to Citizen DJ.

**Comment by beefoo** [comment]
Hello! Apologies for the delay in response.  Due to some technical hurdles, we could not release the Jukebox recordings right on January 1st, _but_ they have since been released and you can now view and use them here:

https://citizen-dj.labs.loc.gov/public-domain-2022/

Thank you and hope you enjoy the new samples!

**Comment by Zyberetro** [comment]
> Hello! Apologies for the delay in response. Due to some technical hurdles, we could not release the Jukebox recordings right on January 1st, _but_ they have since been released and you can now view and use them here:
> 
> https://citizen-dj.labs.loc.gov/public-domain-2022/
> 
> Thank you and hope you enjoy the new samples!

Hey, better late than never, I honestly wasn't expecting a response considering how inactive this forum was (the last thread excluding mine is from over a year ago). I just read the post you linked and I'm honestly excited to try this stuff out. Thank you so much Brian.
